osx_image: xcode8.3

language: objective-c

# Branch Whitelist
branches:
    only:
        - master
        - develop

before_install:
    - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
    - gem install bundler && bundle install

script: "./fastlane/travis.sh"

notifications:
  slack: froghat:rCrsbEuv9RqaqfTHQ46X9v1L