osx_image: xcode11

language: objective-c

# Branch Whitelist
branches:
    only:
        - master
        - develop

before_install:
    - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
    - gem install bundler && bundle install

before_script: bundle exec danger

script: "./fastlane/travis.sh"