# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    before_all do
        git_pull(only_tags: true)
    end
    
    after_all do
        push_git_tags
    end
    
    desc "Description of what the lane does"
    lane :test do
        scan(code_coverage: true)

        swiftlint(
            mode: :lint,                            # SwiftLint mode: :lint (default) or :autocorrect
            ignore_exit_status: true                # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
        )
    end
end
